### ISSUE TITLE
Firefox keyshortcut override

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [dytiger/dytiger.github.io#1]
Firefox 55, when tapping the key ' (left at ENTER)and /(left at right SHIFT) , it will open firefox search bar.

**Comment by dytiger** [comment]
It's OK~ :-)

**Comment by ZhengshuaiPENG** [comment]
"+" "-" "shift" "ctrl" "alt" 
These keys were tapped without responding.

**Comment by dytiger** [comment]
除alt外，其它键响应问题已经解决。
alt会在ff上打开menu。需要在ff上设置。目前还没有找到解决方法。
